- name: Install NGINX on Debian/Ubuntu
  hosts: all
  connection: ssh
  gather_facts: yes
  become: true
  become_method: sudo
  vars_files:
    - /etc/ansible/vars/main.yml
  
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  
  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Deploy website content
    copy:
      src: /etc/ansible/files/sample_website/
      dest: /var/www/html
      mode: 0755
      owner: root

  - name: Create index.html from template
    template:
      src: /etc/ansible/templates/index.html.j2
      dest: /var/www/html/index.nginx-debian.html
      force: yes
  
  - name: Ensure Nginx service is started and enabled
    service:
      name: nginx
      state: restarted
      enabled: yes

  roles:
    - { role: geerlingguy.firewall }
